<!DOCTYPE html>
<html lang="en">

<head>
    <!-- TITLE AND META -->
    <?=$this->getMeta();?>
    <meta name="viewport" content="width=device-width, initial-scale=1">


    <!-- FAV ICONS and WEBFONT -->
    <link rel="icon" href="/images/favicons/favicon.png">
    <link href='https://fonts.googleapis.com/css?family=Libre+Baskerville:400,600|Poppins:400,500,700' rel='stylesheet' type='text/css'>
    <link rel="stylesheet" href="/css/bootstrap.min.css">
    <link rel="stylesheet" href="/admintemp/plugins/fontawesome-free/css/all.min.css">
    <link rel="stylesheet" href="/fonts/archyedt-bold.min.css">


    <!-- ICON FONT -->
    <link rel="stylesheet" href="/public/assets/icons/styles.css">

    <!-- Third Party CSS including Bootstrap -->
    <!-- Third Party CSS including Bootstrap -->
    <link rel="stylesheet" href="/public/css/third-party.css">

    <!-- STYLESHEETS -->
    <link rel="stylesheet" href="/public/css/styles.css">
    <link rel="stylesheet" href="/public/css/responsive.css">

    <!--[if lt IE 9]>
    <script src="/public/js/html5shiv.js"></script>
    <![endif]-->

</head>

<body>

<!-- =========================
 PRE LOADER
============================== -->
<div class="preloader">
    <div class="status">
        <div class="loader">
            <svg class="circular" viewbox="25 25 50 50">
                <circle class="path" cx="50" cy="50" r="20" fill="none" stroke-width="3" stroke-miterlimit="10" />
            </svg>
        </div>
    </div>
</div>

<div class="content">
    <?=$content?>
</div>

<!-- =========================
 SECTION: SUBSCRIBE FORM
============================== -->
<section id="section11" class="subscribe-section">

    <!-- HEADING -->
    <h3 class=" wow fadeInLeft" data-wow-offset="30" data-wow-duration="1.5s" data-wow-delay="0.15s" style="font-family: 'ArchyEDT-Bold', sans-serif;">ჩვენ დაგირეკავთ</h3>
    <h6 class="callsuccess green-text MTMedium" style="background: #e5f2f9">მადლობა, ჩვენ მალე დაგირეკავთ</h6>
    <h6 class="callerror red-text"></h6>
    <!-- SUBSCRIBE FORM -->
    <form id="call-form" class="subscribe-form mailchimp wow fadeInRight" data-wow-offset="30" data-wow-duration="1.5s" data-wow-delay="0.15s">
        <input style="font-family: CITI-Nus-Regular;" type="text" id="phone" name="phone" placeholder="ტელეფონის ნომერი" class="input-box bg-color1">
        <button type="submit" class="btn btn-default standard-button red-button" style="font-family: 'ArchyEDT-Bold', sans-serif;">დამირეკეთ</button>
    </form>

    <!-- ERROR AND SUCCESS MESSAGE - AUTO GENERATED BY MAILCHIMP-->
    <div class="mailchimp-error red-text">
    </div>

    <div class="mailchimp-success green-text">
    </div>

</section>


<!-- =========================
 SECTION: CONTACT US
============================== -->
<section class="get-in-touch" id="section10">
    <div class="container">

        <!-- SECTION HEADER -->
        <div class="section-header">
            <h3 style="font-family: 'ArchyEDT-Bold', sans-serif;">დაგვიკავშირდით</h3>
        </div>

        <div class="row">
            <div class="col-lg-8 col-lg-offset-2">

                <!-- MAIL SUCCESS MESSAGE - ERROR MESSAGE AVAILABLE IN custom.js -->
                <h6 class="success green-text MTMedium" style="background: #e5f2f9">თქვენი შეტყობინება გადმოგზავნილია, მალე გიპასუხებთ</h6>
                <h6 class="error red-text"></h6>

                <form id="contact-form" class="contact-form">
                    <div class="row">

                        <div class="col-lg-6 col-md-6">
                            <input type="text" id="name" name="name" class="input-field" style="font-family: 'ArchyEDT-Bold', sans-serif;" placeholder="სახელი">
                        </div>

                        <div class="col-lg-6 col-md-6">
                            <input type="email" id="email" name="email" class="input-field" style="font-family: 'ArchyEDT-Bold', sans-serif;" placeholder="თქვენი ელ.ფოსტა">
                        </div>

                        <div class="col-lg-6 col-md-6">
                            <input type="text" id="subject" name="subject" class="input-field" style="font-family: 'ArchyEDT-Bold', sans-serif;" placeholder="სათაური">
                        </div>

                        <div class="col-lg-6 col-md-6">
                            <input type="text" id="budget" name="budget" class="input-field" style="font-family: 'ArchyEDT-Bold', sans-serif;" placeholder="ტელეფონის ნომერი">
                        </div>

                        <div class="col-lg-12">
                            <textarea name="message" id="message" class="input-field" rows="8" style="font-family: 'ArchyEDT-Bold', sans-serif;" placeholder="შეტყობინება დაწერეთ აქ"></textarea>
                        </div>

                        <button type="submit" class="btn btn-default standard-button red-button" style="font-family: 'ArchyEDT-Bold', sans-serif;">გადაგზავნა</button>
                    </div>
                </form>

            </div>
        </div>

        <!-- FOOTER -->
        <div class="row no-gutters">
            <div class="footer clearfix">

                <div class="col-lg-3 col-md-3">
                    <div class="footer-col">
                        <div >
                            <img src="/images/logo.png" alt="" style="height: 130px"> <!-- LOGO -->
                        </div>
                    </div>
                </div>

                <div class="col-lg-3 col-md-3">
                    <div class="footer-col">
                        <h6 class="green-text MTRegular">ოფისის მისამართი</h6>
                        <p class="white-text NusMedium">
                            ბათუმი, ჟ. შარტავას ქ. 16
                        </p>
                    </div>
                </div>

                <div class="col-lg-3 col-md-3">
                    <div class="footer-col">
                        <h6 style="color: #00acea" class="MTRegular">დაგვიკავშირდით</h6>
                        <p class="white-text">
                            +995 577 22 47 47 <br>
                            +995 514 67 47 47 <br>
                            +995 514 65 47 47 <br>
                            realpalace2012@gmail.com
                        </p>
                    </div>
                </div>

                <div class="col-lg-3 col-md-3">
                    <div class="footer-col">
                        <h6 class="yellow-text MTRegular">სოც.ქსელები</h6>
                        <div class="social-icons">
                            <a href="https://www.facebook.com/BuildingCompanyREALPALACE/"><span class="icon icon-sb-facebook"></span></a>
                            <a href=""><span class="icon icon-sb-twitter"></span></a>
                            <a href=""><span class="icon icon-sb-instagram"></span></a>
                        </div>
                    </div>
                </div>
            </div>

            <div class="four-lines">
                <div class="line red-line-bottom">
                </div>
                <div class="line green-line-bottom">
                </div>
                <div class="line purple-line-bottom">
                </div>
                <div class="line yellow-line-bottom">
                </div>
            </div>

        </div>
    </div>
</section>

<!-- =========================
 JS SCRIPTS
============================== -->
<script src="/public/js/jquery-1.11.3.min.js"></script>
<script src="/public/js/third-party-scripts.js"></script>
<script src="/public/js/custom.js"></script>
<script src="/public/js/main.js"></script>
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.0/js/bootstrap.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/wow/0.1.12/wow.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/2.1.3/jquery.min.js"></script>
</body>

</html>
